### ISSUE TITLE
Si5351 Calibration

### ISSUE THREAD

**Issue by k7ilo** [W3PM/GPS-VFO#1]
Hey Gene
Now that Ive learned a bit about Arduino and your code, I have returned to the core of your software and I'm having issues calibrating the Si5351 with the int CalFactor parameter.

I set the Si5351 to 25Mhz using the Freq_Array entering 25000000 which my counter is reading 24902550 so following your math instructions, the calculator says -97450.  I enter that as my CalFactor=-97450 and the counter goes to 24934.380.  The problem is, I'm still nowhere near 25Mhz and if I adjust my CalFactor by much in either direction, the frequency drops much lower.

If I use any other cal program or another VFO code that uses any other Si5351 library, all works fine so Im not sure if there is some calculation issues in the Si5351 coding you have in the software.

I'm using a Adafruit Si5351 version if this makes a difference.  Am I missing something Gene?
I have not tried it with GPS correction yet because I wanted to use it for now without while its on the test bench.

Thanks

**Comment by W3PM** [comment]
New batches of the Si5351 IC now default to spread spectrum mode. To disable the spread spectrum mode register 149 D7 must be set to 0.  Sketches Si5351_vfo_v5_3b-i2c and Si5351_vfo_v5_3b have been updated to disable the spread spectrum function.
